config/routes.rb
App::Application.routes.draw do
  resources :authentications

  resources :roles

  resources :organizations

  resources :projects

  resources :labels

  resources :milestones

  resources :issues

  resources :bids

  resources :bounties

  get '/about' => 'pages#about'

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
    controllers: {
      omniauth_callbacks: "omniauth_callbacks",
      registrations: "registrations"
    }

  root to: 'projects#show', github_name: 'debate'

  

end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  has_many :issues
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  before_action :set_milestone, only: [:show, :edit, :update, :destroy]

  # GET /milestones
  # GET /milestones.json
  def index
    @milestones = Milestone.all
  end

  # GET /milestones/1
  # GET /milestones/1.json
  def show
  end

  # GET /milestones/new
  def new
    @milestone = Milestone.new
  end

  # GET /milestones/1/edit
  def edit
  end

  # POST /milestones
  # POST /milestones.json
  def create
    @milestone = Milestone.new(milestone_params)

    respond_to do |format|
      if @milestone.save
        format.html { redirect_to @milestone, notice: 'Milestone was successfully created.' }
        format.json { render action: 'show', status: :created, location: @milestone }
      else
        format.html { render action: 'new' }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /milestones/1
  # PATCH/PUT /milestones/1.json
  def update
    respond_to do |format|
      if @milestone.update(milestone_params)
        format.html { redirect_to @milestone, notice: 'Milestone was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /milestones/1
  # DELETE /milestones/1.json
  def destroy
    @milestone.destroy
    respond_to do |format|
      format.html { redirect_to milestones_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_milestone
      @milestone = Milestone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def milestone_params
      params.require(:milestone).permit(:name)
    end
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/views/milestones/_form.html.haml
= form_for @milestone do |f|
  - if @milestone.errors.any?
    #error_explanation
      %h2= "#{pluralize(@milestone.errors.count, "error")} prohibited this milestone from being saved:"
      %ul
        - @milestone.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/milestones/edit.html.haml
%h1 Editing milestone

= render 'form'

= link_to 'Show', @milestone
\|
= link_to 'Back', milestones_path

app/views/milestones/index.html.haml
%h1 Listing milestones

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @milestones.each do |milestone|
    %tr
      %td= milestone.name
      %td= link_to 'Show', milestone
      %td= link_to 'Edit', edit_milestone_path(milestone)
      %td= link_to 'Destroy', milestone, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Milestone', new_milestone_path

app/views/milestones/new.html.haml
%h1 New milestone

= render 'form'

= link_to 'Back', milestones_path

app/views/milestones/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @milestone.name

= link_to 'Edit', edit_milestone_path(@milestone)
\|
= link_to 'Back', milestones_path