config/routes.rb
App::Application.routes.draw do
  resources :authentications

  resources :roles

  resources :organizations

  resources :projects

  resources :labels

  resources :milestones

  resources :issues

  resources :bids

  resources :bounties

  get '/about' => 'pages#about'

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
    controllers: {
      omniauth_callbacks: "omniauth_callbacks",
      registrations: "registrations"
    }

  root to: 'projects#show', github_name: 'debate'

  

end

app/models/bounty.rb
class Bounty < ActiveRecord::Base
  has_one :poster, class_name: 'User'
  belongs_to :issue

  # rails 4.1
  # enum currency: [ :btc, :usd ]
end

app/controllers/bounties_controller.rb
class BountiesController < ApplicationController
  before_action :set_bounty, only: [:show, :edit, :update, :destroy]

  # GET /bounties
  # GET /bounties.json
  def index
    @bounties = Bounty.all
  end

  # GET /bounties/1
  # GET /bounties/1.json
  def show
  end

  # GET /bounties/new
  def new
    @bounty = Bounty.new

    @bounty.issue = Issue.find params[:issue] if params[:issue]
  end

  # GET /bounties/1/edit
  def edit
  end

  # POST /bounties
  # POST /bounties.json
  def create
    @bounty = Bounty.new(bounty_params)

    respond_to do |format|
      if @bounty.save
        format.html { redirect_to @bounty, notice: 'Bounty was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bounty }
      else
        format.html { render action: 'new' }
        format.json { render json: @bounty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bounties/1
  # PATCH/PUT /bounties/1.json
  def update
    respond_to do |format|
      if @bounty.update(bounty_params)
        format.html { redirect_to @bounty, notice: 'Bounty was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bounty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bounties/1
  # DELETE /bounties/1.json
  def destroy
    @bounty.destroy
    respond_to do |format|
      format.html { redirect_to bounties_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bounty
      @bounty = Bounty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bounty_params
      params.require(:bounty).permit(:expiration, :amount, :currency, :poster)
    end
end

app/helpers/bounties_helper.rb
module BountiesHelper
end

app/views/bounties/_form.html.haml
= form_for @bounty do |f|
  - if @bounty.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bounty.errors.count, "error")} prohibited this bounty from being saved:"
      %ul
        - @bounty.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :expiration
    = f.date_field :expiration
  .field
    = f.label :amount
    = f.text_field :amount
  .field
    = f.label :currency
    = f.number_field :currency
  .field
    = f.label :poster
    = f.text_field :poster
  .actions
    = f.submit 'Save'

app/views/bounties/edit.html.haml
%h1 Editing bounty

= render 'form'

= link_to 'Show', @bounty
\|
= link_to 'Back', bounties_path

app/views/bounties/index.html.haml
%h1 Listing bounties

%table
  %tr
    %th Expiration
    %th Amount
    %th Currency
    %th Poster
    %th
    %th
    %th

  - @bounties.each do |bounty|
    %tr
      %td= bounty.expiration
      %td= bounty.amount
      %td= bounty.currency
      %td= bounty.poster
      %td= link_to 'Show', bounty
      %td= link_to 'Edit', edit_bounty_path(bounty)
      %td= link_to 'Destroy', bounty, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Bounty', new_bounty_path

app/views/bounties/new.html.haml
%h1 New bounty

= render 'form'

= link_to 'Back', bounties_path

app/views/bounties/show.html.haml
%p#notice= notice

%p
  %b Expiration:
  = @bounty.expiration
%p
  %b Amount:
  = @bounty.amount
%p
  %b Currency:
  = @bounty.currency
%p
  %b Poster:
  = @bounty.poster

= link_to 'Edit', edit_bounty_path(@bounty)
\|
= link_to 'Back', bounties_path