config/routes.rb
App::Application.routes.draw do
  resources :authentications

  resources :roles

  resources :organizations

  resources :projects

  resources :labels

  resources :milestones

  resources :issues

  resources :bids

  resources :bounties

  get '/about' => 'pages#about'

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
    controllers: {
      omniauth_callbacks: "omniauth_callbacks",
      registrations: "registrations"
    }

  root to: 'projects#show', github_name: 'debate'

  

end

app/models/project.rb
require 'open-uri'

class Project < ActiveRecord::Base
  belongs_to :owner, class_name: 'User'
  has_many :assignments
  has_many :organizations, through: :assignments
  has_many :issues

  def self.load_from_github params
    info = JSON.parse open("https://api.github.com/repos/%s/%s" % [params[:owner], params[:github_name]]).read

    project = Project.find_or_create_by id: info['id']

    project.github_name = params[:github_name]
    project.name = params[:github_name].gsub(/_/, ' ').titleize
    project.description = info['description']
    project.owner = User.find_or_create_by username: params[:owner]

    project.reload_issues

    project.save
  end

  def reload_issues
    issues = JSON.parse open("https://api.github.com/repos/%s/%s/issues" % [owner.username, github_name]).read

    issues.each do |issue_res|
      issue = Issue.find_or_create_by project: self, github_id: issue_res['number']
      issue.name = issue_res['title']
      issue.url = issue_res['html_url']
      issue.milestone = Milestone.find_or_create_by name: issue_res.try(:[], 'milestone').try(:[], 'title')
      issue.description = issue_res['body']
      issue.save
    end
  end
end

app/controllers/projects_controller.rb
require 'pp'

class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find_by github_name: params[:github_name] if params[:github_name]
    @project ||= Project.find params[:id]
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.load_from_github project_params

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:github_name, :name, :owner)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :github_name
    = f.text_field :github_name
  .field
    = f.label :owner
    = f.text_field :owner
  .actions
    = f.submit 'Save'

app/views/projects/_issue_cells.html.haml
%td= issue.name
%td= issue.bids.collect(&:min).min
%td= issue.bids.collect(&:max).max
= form_for Bid.new(issue: issue), class: :estimate do |f|
  %td= f.text_field :min
  %td= f.text_field :max

app/views/projects/_table.html.haml
%table.table.table-striped
  %thead
    %tr
      %th{ colspan: 3 }= link_to @project.name, @project
    %tr
      %th Name
      %th Bids
      %th Bounties
  %tbody
    - @project.issues.each do |issue|
      %tr
        %td= link_to issue.name, issue.url
        %td= link_to (issue.leading_bid ? number_to_currency(issue.leading_bid.try(:amount)) : '✖'), new_bid_path(issue: issue.id)
        %td= link_to number_to_currency(issue.total_bounties), new_bounty_path(issue: issue.id)

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1 Listing projects

%table
  %tr
    %th Github name
    %th Name
    %th Owner
    %th
    %th
    %th

  - @projects.each do |project|
    %tr
      %td= project.github_name
      %td= project.name
      %td= project.owner.github_name
      %td= link_to 'Show', project
      %td= link_to 'Edit', edit_project_path(project)
      %td= link_to 'Destroy', project, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Project', new_project_path

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
- if not @project
  %p No project
- else
  #project
    %p#notice= notice

    %h1= link_to @project.github_name, 'https://github.com/%s/%s' % [@project.owner.username, @project.github_name]

    %p= @project.description

    - if @project.issues.any?
      .row
        .col-xs-offset-1.col-xs-6 Issue
        .col-xs-2 Contributed Estimates
        - if user_signed_in?
          .col-xs-2 Your Estimates
          .col-xs-1
            Rate
            %em ($/hr)
      .row
        .col-xs-offset-7.col-xs-1 Min
        .col-xs-1 Max
        - if user_signed_in?
          .col-xs-1 Min
          .col-xs-1 Max
          
      - @project.issues.sort_by{ |i| i.milestone.name || 'None' }.group_by(&:milestone).each do |milestone, issues|
        .row
          .milestone.col-xs-12= milestone.name || 'None'
        - issues.each do |issue|
          .row
            .col-xs-offset-1.col-xs-6= link_to issue.name, issue
            .col-xs-1= issue.bids.collect(&:min).min
            .col-xs-1= issue.bids.collect(&:max).max
            - if user_signed_in?
              - bid = issue.bids.where(bidder: current_user).first || Bid.new(issue: issue, bidder: current_user)
              = form_for bid, html: { class: :estimate } do |f|
                = f.hidden_field :issue_id
                .col-xs-1= f.text_field :min
                .col-xs-1= f.text_field :max
                .col-xs-1= f.text_field :rate, value: bid.rate