config/routes.rb
App::Application.routes.draw do
  resources :authentications

  resources :roles

  resources :organizations

  resources :projects

  resources :labels

  resources :milestones

  resources :issues

  resources :bids

  resources :bounties

  get '/about' => 'pages#about'

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
    controllers: {
      omniauth_callbacks: "omniauth_callbacks",
      registrations: "registrations"
    }

  root to: 'projects#show', github_name: 'debate'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
    user ||= User.new # guest user
    
    if user.role? :admin
      can :manage, :all
    else
      can :read, :all
      can :create, [Bid, Bounty]
      cannot :read, User

      if user.role? :manager
        can :manage, [Organization, Project, Issue, Bid, Bounty]
      end
    end
  end
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :organization
  belongs_to :project
end

app/models/association.rb
class Association < ActiveRecord::Base
  belongs_to :organization
  belongs_to :project
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :bidder, class_name: 'User'
  belongs_to :issue

  def rate
    self[:rate] or bidder.rate
  end
end

app/models/bounty.rb
class Bounty < ActiveRecord::Base
  has_one :poster, class_name: 'User'
  belongs_to :issue

  # rails 4.1
  # enum currency: [ :btc, :usd ]
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :project
  belongs_to :milestone
  has_many :bids
  has_many :bounties
  has_many :labels

  def leading_bid
    bids.first
  end

  def total_bounties
    bounties.collect(&:amount).sum
  end

  def url
    'http://github.com/%s/%s/issues/%s' % [project.owner.username, project.github_name, github_id]
  end
end

app/models/label.rb
class Label < ActiveRecord::Base
  has_many :issues
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  has_many :issues
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :assignments
  has_many :projects, through: :assignments
end

app/models/project.rb
require 'open-uri'

class Project < ActiveRecord::Base
  belongs_to :owner, class_name: 'User'
  has_many :assignments
  has_many :organizations, through: :assignments
  has_many :issues

  def self.load_from_github params
    info = JSON.parse open("https://api.github.com/repos/%s/%s" % [params[:owner], params[:github_name]]).read

    project = Project.find_or_create_by id: info['id']

    project.github_name = params[:github_name]
    project.name = params[:github_name].gsub(/_/, ' ').titleize
    project.description = info['description']
    project.owner = User.find_or_create_by username: params[:owner]

    project.reload_issues

    project.save
  end

  def reload_issues
    issues = JSON.parse open("https://api.github.com/repos/%s/%s/issues" % [owner.username, github_name]).read

    issues.each do |issue_res|
      issue = Issue.find_or_create_by project: self, github_id: issue_res['number']
      issue.name = issue_res['title']
      issue.url = issue_res['html_url']
      issue.milestone = Milestone.find_or_create_by name: issue_res.try(:[], 'milestone').try(:[], 'title')
      issue.description = issue_res['body']
      issue.save
    end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, -> { uniq }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable
  # :validatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :omniauthable

  validates_uniqueness_of :email, case_sensitive: false, allow_blank: true, if: :email_changed?
  validates_format_of :email, with: Devise.email_regexp, allow_blank: true, if: :email_changed?
  validates_confirmation_of :password, on: :create
  validates_length_of :password, within: Devise.password_length, allow_blank: true

  has_and_belongs_to_many :roles, -> { uniq }
  has_many :projects, class_name: 'Project', foreign_key: 'owner_id'
  has_many :organizations
  has_many :bounties
  has_many :bids
  has_many :authentications

  def full_name
    email || 'No Name'
  end

  def role? role
    roles.collect(&:name).map(&:downcase).include? role.to_s
  end
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/bounties_helper.rb
module BountiesHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/layouts/application.html.haml
== <!DOCTYPE html>
%html{:'xmlns:fb' => 'http://ogp.me/ns/fb#'}
  %head
    %title Crowdfund
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    =# favicon_link_tag 'favicon.png', rel: 'icon', type: 'image/png'
  %body
    .navbar.navbar-default.navbar-fixed-top{role: 'navigation'}
      .container
        .navbar-header
          %button.navbar-toggle{ data: { toggle: 'collapse', target: '.navbar-collapse' } }
            %span.sr-only Toggle navigation
            %span.icon-bar
          = link_to root_path, class: 'navbar-brand' do
            = image_tag 'http://dhappy.org/.../image/logo/One%20Acre%20Cafe/', id: 'logo'
            Crowdfund
        .navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li
            -# %li{ class: params[:controller] == 'bounties' ? 'active dropdown' : 'dropdown' }
              %a.dropdown-toggle{ href: '#', data: { toggle: 'dropdown' } }
                Bounties
                %b.caret
              %ul.dropdown-menu
                %li.tabled
                  = link_to 'View All', bounties_path, class: :iconed
                - if can? :create, Bounty or can? :destroy, Bounty
                  %li.divider
                - if can? :create, Bounty
                  %li= link_to 'New', new_bounty_path
                - if can? :destroy, Bounty
                  %li= link_to 'Delete', delete_bounties_path

            -# %li{ class: params[:controller] == 'bids' ? 'active dropdown' : 'dropdown' }
              %a.dropdown-toggle{ href: '#', data: { toggle: 'dropdown' } }
                Bids
                %b.caret
              %ul.dropdown-menu
                %li.tabled
                  = link_to 'View All', bids_path, class: :iconed
                - if can? :create, Bid or can? :destroy, Bid
                  %li.divider
                - if can? :create, Bid
                  %li= link_to 'New', new_bid_path
                - if can? :destroy, Bid
                  %li= link_to 'Delete', delete_bids_path

            - if can? :read, User
              %li{ class: params[:controller] == 'users' ? 'active dropdown' : 'dropdown' }
                %a.dropdown-toggle{ href: '#', data: { toggle: 'dropdown' } }
                  Users
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to 'List', users_path
                  - if can? :create, User
                    %li= link_to 'New', new_user_path
                  - if current_user.try(:role?, :admin)
                    %li= link_to 'Roles', roles_path

            %li{ class: (params[:controller] == 'pages' and params[:action] == 'about') ? 'active' : nil }
              = link_to 'About', about_path

          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li= link_to current_user.full_name, edit_user_registration_path
              %li= link_to "Logout", destroy_user_session_path, method: :delete
            - else
              %li= link_to "Login", omniauth_authorize_path( 'user', 'github' )

    .container
      %p#notice.alert.alert-info.hide= notice
      %p#alert.alert.alert-danger.hide= alert

      = yield

app/views/pages/about.html.haml
#about
  %h1 About

  %p
    :markdown
      This software is [open source](https://github.com/dhappy/crowdfund).